version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production